Class10/Models/ErrorViewModel.cs
namespace Class10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Class10/Controllers/HomeController.cs
using Class10.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Class10.Filters;

namespace Class10.Controllers
{
    [DailyMaintenanceFilter(From = new[] {22,30,0}, To = new[] {3,59,59})]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Class10/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;

namespace Class10.Controllers
{
    public class SecurityController : Controller
    {
        public IActionResult Maintenance()
        {
            HttpContext.Response.StatusCode = 405;
            return View();
        }
    }
}

Class10/Controllers/TestCacheController.cs
using Microsoft.AspNetCore.Mvc;

namespace Class10.Controllers
{
    public class TestCacheController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration =20,Location =ResponseCacheLocation.Client)]
        public IActionResult OnClient()
        {
            return View();
        }

        [ResponseCache(Duration = 40, Location = ResponseCacheLocation.Any)]
        public IActionResult OnDownStream()
        {
            return View();
        }

        [ResponseCache(CacheProfileName = "TestCacheProfile")]
        public IActionResult WithHeaders()
         {
            return View();
        }
    }
    
}

Class10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Class10/Views/Security/Maintenance.cshtml
@{
    ViewData["Title"] = "Maintenance";
}

<h1>Site Maintenance</h1>

<img src="~/images/maintenance.gif" width="30%" height="30%"/>

<p>This site it´s closed to daily maintenance.</p>
<p>We are sorry for the inconvenience. Please come back later.</p>

Class10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Class10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Class10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Class10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestCache" asp-action="OnClient">OnClient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestCache" asp-action="OnDownStream">OnDownStream</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestCache" asp-action="WithHeaders">VaryByHeaders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Class10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Class10/Views/TestCache/OnClient.cshtml
@{
    ViewData["Title"] = "OnClient";
}

<h1>OnClient</h1>

This view was built at @DateTime.Now.ToLongTimeString()

Class10/Views/TestCache/OnDownStream.cshtml
@{
    ViewData["Title"] = "OnDownStream";
}

<h1>OnDownStream</h1>

This view was built at @DateTime.Now.ToLongTimeString()

Class10/Views/TestCache/WithHeaders.cshtml
@{
    ViewData["Title"] = "WithHeaders";
}

<h1>VaryByHeaders</h1>

Value sended in header is: @Context.Response.Headers["Vary"]
<br /><br />
This view was built at <strong>@DateTime.Now.ToLongTimeString()</strong>
<br />

<h3>Header value</h3>
@Context.Response.Headers["Vary"] : @Context.Request.Headers[Context.Response.Headers["Vary"]]